version: '3.8'
services:
  localstack: 
    image: localstack/localstack:latest
    environment: 
      - DEFAULT_REGION=ap-northeast-2
      - EDGE_PORT=4566
      - SERVICES=s3,lambda,logs
    ports: 
      - '4566-4583:4566-4583'
  web:
    build: .
    ports:
      - '3000:3000'
